/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext,
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { CategoryDeletionRiskResponse } from '../model/categoryDeletionRiskResponse';
// @ts-ignore
import { HTTPValidationError } from '../model/hTTPValidationError';
// @ts-ignore
import { MODEL_REFERENCE_CATEGORY } from '../model/mODELREFERENCECATEGORY';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
  providedIn: 'root',
})
export class DeletionRiskService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration,
  ) {
    super(basePath, configuration);
  }

  /**
   * Get deletion risk analysis for a model category
   * Get comprehensive deletion risk analysis for a model reference category.  Analyzes all models in the category to identify deletion risks including: - Missing or invalid download URLs - Non-preferred file hosts - Missing required fields (description, baseline) - Zero active workers - Low or no recent usage  Returns both per-model risk information and aggregate summary statistics. Results are cached (default 300s TTL) and automatically invalidated when model data changes.  Args:     model_category_name: The model reference category to analyze.     manager: The model reference manager (injected).     horde_api: The Horde API integration (injected).     risk_cache: The deletion risk cache (injected).     group_text_models: Group text models by base name (strips quantization info).     include_backend_variations: Include per-backend breakdown for text models (ungrouped view).     preset: Optional preset filter to apply (deletion_candidates, zero_usage, etc.).     limit: Maximum number of models to return (None &#x3D; all).     offset: Number of models to skip (for pagination).  Returns:     CategoryDeletionRiskResponse with per-model risk info and summary.  Raises:     HTTPException: 400 for unsupported categories or invalid preset, 404 if not found, 500 for errors.
   * @param modelCategoryName
   * @param groupTextModels Group text models by base name (strips quantization)
   * @param includeBackendVariations Include per-backend breakdown (aphrodite, koboldcpp) for text models. Only applies when group_text_models&#x3D;False.
   * @param preset Apply preset filter to results. Valid presets: deletion_candidates, zero_usage, no_workers, missing_data, host_issues, critical, low_usage
   * @param limit Maximum number of models to return (None &#x3D; all)
   * @param offset Number of models to skip (for pagination)
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public readV2CategoryDeletionRisk(
    modelCategoryName: MODEL_REFERENCE_CATEGORY,
    groupTextModels?: boolean,
    includeBackendVariations?: boolean,
    preset?: string,
    limit?: number,
    offset?: number,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<CategoryDeletionRiskResponse>;
  public readV2CategoryDeletionRisk(
    modelCategoryName: MODEL_REFERENCE_CATEGORY,
    groupTextModels?: boolean,
    includeBackendVariations?: boolean,
    preset?: string,
    limit?: number,
    offset?: number,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<CategoryDeletionRiskResponse>>;
  public readV2CategoryDeletionRisk(
    modelCategoryName: MODEL_REFERENCE_CATEGORY,
    groupTextModels?: boolean,
    includeBackendVariations?: boolean,
    preset?: string,
    limit?: number,
    offset?: number,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<CategoryDeletionRiskResponse>>;
  public readV2CategoryDeletionRisk(
    modelCategoryName: MODEL_REFERENCE_CATEGORY,
    groupTextModels?: boolean,
    includeBackendVariations?: boolean,
    preset?: string,
    limit?: number,
    offset?: number,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    if (modelCategoryName === null || modelCategoryName === undefined) {
      throw new Error(
        'Required parameter modelCategoryName was null or undefined when calling readV2CategoryDeletionRisk.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>groupTextModels,
      'group_text_models',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>includeBackendVariations,
      'include_backend_variations',
    );
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>preset, 'preset');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>limit, 'limit');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>offset, 'offset');

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/model_references/statistics/${this.configuration.encodeParam({ name: 'modelCategoryName', value: modelCategoryName, in: 'path', style: 'simple', explode: false, dataType: 'MODEL_REFERENCE_CATEGORY', dataFormat: undefined })}/deletion-risk`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<CategoryDeletionRiskResponse>(
      'get',
      `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters,
        responseType: <any>responseType_,
        ...(withCredentials ? { withCredentials } : {}),
        headers: localVarHeaders,
        observe: observe,
        transferCache: localVarTransferCache,
        reportProgress: reportProgress,
      },
    );
  }
}
