/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
  HttpParameterCodec,
  HttpContext,
} from '@angular/common/http';
import { CustomHttpParameterCodec } from '../encoder';
import { Observable } from 'rxjs';

// @ts-ignore
import { HTTPValidationError } from '../model/hTTPValidationError';
// @ts-ignore
import { PermissionStatus } from '../model/permissionStatus';
// @ts-ignore
import { SearchResponse } from '../model/searchResponse';

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';
import { BaseService } from '../api.base.service';

@Injectable({
  providedIn: 'root',
})
export class SearchService extends BaseService {
  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | string[],
    @Optional() configuration?: Configuration,
  ) {
    super(basePath, configuration);
  }

  /**
   * Get popular models ranked by live Horde usage
   * Return models ranked by live Horde popularity metrics.  Only &#x60;&#x60;image_generation&#x60;&#x60; and &#x60;&#x60;text_generation&#x60;&#x60; have Horde API data. Other categories return an empty list.
   * @param modelCategoryName
   * @param limit Max results
   * @param sortBy Metric to rank by
   * @param includeWorkers Include per-worker details
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public popularModelsModelReferencesV2ModelCategoryNamePopularGet(
    modelCategoryName: string,
    limit?: number,
    sortBy?: 'worker_count' | 'usage_day' | 'usage_month' | 'usage_total',
    includeWorkers?: boolean,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<Array<object>>;
  public popularModelsModelReferencesV2ModelCategoryNamePopularGet(
    modelCategoryName: string,
    limit?: number,
    sortBy?: 'worker_count' | 'usage_day' | 'usage_month' | 'usage_total',
    includeWorkers?: boolean,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<Array<object>>>;
  public popularModelsModelReferencesV2ModelCategoryNamePopularGet(
    modelCategoryName: string,
    limit?: number,
    sortBy?: 'worker_count' | 'usage_day' | 'usage_month' | 'usage_total',
    includeWorkers?: boolean,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<Array<object>>>;
  public popularModelsModelReferencesV2ModelCategoryNamePopularGet(
    modelCategoryName: string,
    limit?: number,
    sortBy?: 'worker_count' | 'usage_day' | 'usage_month' | 'usage_total',
    includeWorkers?: boolean,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    if (modelCategoryName === null || modelCategoryName === undefined) {
      throw new Error(
        'Required parameter modelCategoryName was null or undefined when calling popularModelsModelReferencesV2ModelCategoryNamePopularGet.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>limit, 'limit');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>sortBy, 'sort_by');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>includeWorkers,
      'include_workers',
    );

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/model_references/v2/${this.configuration.encodeParam({ name: 'modelCategoryName', value: modelCategoryName, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/popular`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<Array<object>>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress,
    });
  }

  /**
   * Search models across all categories
   * Search models across all categories with generic filters only.
   * @param nsfw Filter by NSFW status
   * @param nameContains Case-insensitive name substring match
   * @param tagsAny Models with any of these tags
   * @param tagsAll Models with all of these tags
   * @param tagsNone Models with none of these tags
   * @param sortBy Field name to sort by
   * @param sortDesc Sort descending
   * @param limit Max results to return
   * @param offset Number of results to skip
   * @param licenseId Referenced license definition identifier
   * @param commercialUse Commercial-use conclusion
   * @param redistribution Redistribution conclusion
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public searchAllModelReferencesV2SearchGet(
    nsfw?: boolean,
    nameContains?: string,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<SearchResponse>;
  public searchAllModelReferencesV2SearchGet(
    nsfw?: boolean,
    nameContains?: string,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<SearchResponse>>;
  public searchAllModelReferencesV2SearchGet(
    nsfw?: boolean,
    nameContains?: string,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<SearchResponse>>;
  public searchAllModelReferencesV2SearchGet(
    nsfw?: boolean,
    nameContains?: string,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>nsfw, 'nsfw');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>nameContains,
      'name_contains',
    );
    if (tagsAny) {
      tagsAny.forEach((element) => {
        localVarQueryParameters = this.addToHttpParams(
          localVarQueryParameters,
          <any>element,
          'tags_any',
        );
      });
    }
    if (tagsAll) {
      tagsAll.forEach((element) => {
        localVarQueryParameters = this.addToHttpParams(
          localVarQueryParameters,
          <any>element,
          'tags_all',
        );
      });
    }
    if (tagsNone) {
      tagsNone.forEach((element) => {
        localVarQueryParameters = this.addToHttpParams(
          localVarQueryParameters,
          <any>element,
          'tags_none',
        );
      });
    }
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>sortBy, 'sort_by');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>sortDesc,
      'sort_desc',
    );
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>limit, 'limit');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>offset, 'offset');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>licenseId,
      'license_id',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>commercialUse,
      'commercial_use',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>redistribution,
      'redistribution',
    );

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/model_references/v2/search`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<SearchResponse>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress,
    });
  }

  /**
   * Search models in a category
   * Search models within a specific category with filtering, sorting, and pagination.
   * @param modelCategoryName
   * @param nsfw Filter by NSFW status
   * @param baseline Filter by baseline
   * @param inpainting Filter by inpainting (image only)
   * @param tagsAny Models with any of these tags
   * @param tagsAll Models with all of these tags
   * @param tagsNone Models with none of these tags
   * @param nameContains Case-insensitive name substring match
   * @param sortBy Field name to sort by
   * @param sortDesc Sort descending
   * @param limit Max results to return
   * @param offset Number of results to skip
   * @param backend Text model backend filter
   * @param excludeBackendVariations Exclude text model backend variations
   * @param quantized Filter by quantization (text only)
   * @param source Model source: \&#39;horde\&#39; (canonical), \&#39;any\&#39;, or a registered provider source id
   * @param licenseId Referenced license definition identifier
   * @param commercialUse Commercial-use conclusion
   * @param redistribution Redistribution conclusion
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public searchCategoryModelReferencesV2ModelCategoryNameSearchGet(
    modelCategoryName: string,
    nsfw?: boolean,
    baseline?: string,
    inpainting?: boolean,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    nameContains?: string,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    backend?: string,
    excludeBackendVariations?: boolean,
    quantized?: boolean,
    source?: string,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe?: 'body',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<SearchResponse>;
  public searchCategoryModelReferencesV2ModelCategoryNameSearchGet(
    modelCategoryName: string,
    nsfw?: boolean,
    baseline?: string,
    inpainting?: boolean,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    nameContains?: string,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    backend?: string,
    excludeBackendVariations?: boolean,
    quantized?: boolean,
    source?: string,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe?: 'response',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpResponse<SearchResponse>>;
  public searchCategoryModelReferencesV2ModelCategoryNameSearchGet(
    modelCategoryName: string,
    nsfw?: boolean,
    baseline?: string,
    inpainting?: boolean,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    nameContains?: string,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    backend?: string,
    excludeBackendVariations?: boolean,
    quantized?: boolean,
    source?: string,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe?: 'events',
    reportProgress?: boolean,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<HttpEvent<SearchResponse>>;
  public searchCategoryModelReferencesV2ModelCategoryNameSearchGet(
    modelCategoryName: string,
    nsfw?: boolean,
    baseline?: string,
    inpainting?: boolean,
    tagsAny?: Array<string>,
    tagsAll?: Array<string>,
    tagsNone?: Array<string>,
    nameContains?: string,
    sortBy?: string,
    sortDesc?: boolean,
    limit?: number,
    offset?: number,
    backend?: string,
    excludeBackendVariations?: boolean,
    quantized?: boolean,
    source?: string,
    licenseId?: string,
    commercialUse?: PermissionStatus,
    redistribution?: PermissionStatus,
    observe: any = 'body',
    reportProgress: boolean = false,
    options?: {
      httpHeaderAccept?: 'application/json';
      context?: HttpContext;
      transferCache?: boolean;
    },
  ): Observable<any> {
    if (modelCategoryName === null || modelCategoryName === undefined) {
      throw new Error(
        'Required parameter modelCategoryName was null or undefined when calling searchCategoryModelReferencesV2ModelCategoryNameSearchGet.',
      );
    }

    let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>nsfw, 'nsfw');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>baseline,
      'baseline',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>inpainting,
      'inpainting',
    );
    if (tagsAny) {
      tagsAny.forEach((element) => {
        localVarQueryParameters = this.addToHttpParams(
          localVarQueryParameters,
          <any>element,
          'tags_any',
        );
      });
    }
    if (tagsAll) {
      tagsAll.forEach((element) => {
        localVarQueryParameters = this.addToHttpParams(
          localVarQueryParameters,
          <any>element,
          'tags_all',
        );
      });
    }
    if (tagsNone) {
      tagsNone.forEach((element) => {
        localVarQueryParameters = this.addToHttpParams(
          localVarQueryParameters,
          <any>element,
          'tags_none',
        );
      });
    }
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>nameContains,
      'name_contains',
    );
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>sortBy, 'sort_by');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>sortDesc,
      'sort_desc',
    );
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>limit, 'limit');
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>offset, 'offset');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>backend,
      'backend',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>excludeBackendVariations,
      'exclude_backend_variations',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>quantized,
      'quantized',
    );
    localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>source, 'source');
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>licenseId,
      'license_id',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>commercialUse,
      'commercial_use',
    );
    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      <any>redistribution,
      'redistribution',
    );

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined =
      options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept(['application/json']);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/model_references/v2/${this.configuration.encodeParam({ name: 'modelCategoryName', value: modelCategoryName, in: 'path', style: 'simple', explode: false, dataType: 'string', dataFormat: undefined })}/search`;
    const { basePath, withCredentials } = this.configuration;
    return this.httpClient.request<SearchResponse>('get', `${basePath}${localVarPath}`, {
      context: localVarHttpContext,
      params: localVarQueryParameters,
      responseType: <any>responseType_,
      ...(withCredentials ? { withCredentials } : {}),
      headers: localVarHeaders,
      observe: observe,
      transferCache: localVarTransferCache,
      reportProgress: reportProgress,
    });
  }
}
