/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParametersValue } from './parametersValue';

/**
 * Validated example for the AI Horde text generation request surface.
 */
export interface AIHordeRequestExample {
  title: string;
  prompt: string;
  parameters?: { [key: string]: ParametersValue };
  notes?: string | null;
}
