/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingChangeRecord } from './pendingChangeRecord';

/**
 * Response payload summarizing a bulk apply attempt.  Batch Split Semantics: When a partial apply occurs (some changes in a batch are applied while others remain), the remaining APPROVED changes are automatically reassigned to a new batch ID. This information is provided in the batch_split_* fields to help clients update their UI.
 */
export interface ApplyPendingChangesResponse {
  applied?: Array<PendingChangeRecord>;
  failed_change_id?: number | null;
  failed_error?: string | null;
  failed_error_type?: string | null;
  /**
   * True if applying changes triggered a batch split (remaining changes reassigned)
   */
  batch_split_occurred?: boolean;
  batch_split_original_batch_id?: number | null;
  batch_split_new_batch_id?: number | null;
  batch_split_reassigned_count?: number | null;
}
