/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KNOWN_IMAGE_GENERATION_BASELINE } from './kNOWNIMAGEGENERATIONBASELINE';

export interface Baseline {}
