/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuditDomain } from './auditDomain';
import { ModelNetChange } from './modelNetChange';

/**
 * Response containing net changes for all models in a batch.
 */
export interface BatchNetChangeResponse {
  batch_id: number;
  batch_title?: string | null;
  domain: AuditDomain;
  model_changes?: Array<ModelNetChange>;
  models_added?: number;
  models_modified?: number;
  models_deleted?: number;
  models_unchanged?: number;
  total_field_changes?: number;
  has_critical_changes?: boolean;
  generated_at: number;
}
export namespace BatchNetChangeResponse {}
