/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryAuditSummary } from './categoryAuditSummary';
import { ModelAuditInfo } from './modelAuditInfo';
import { MODEL_REFERENCE_CATEGORY } from './mODELREFERENCECATEGORY';

/**
 * Complete audit response for a category.  Contains both per-model audit information and aggregate summary.
 */
export interface CategoryAuditResponse {
  /**
   * The category being audited.
   */
  category: MODEL_REFERENCE_CATEGORY;
  /**
   * Total monthly usage for the entire category.
   */
  category_total_month_usage: number;
  /**
   * Total number of models in the category (before pagination/filtering).
   */
  total_count?: number;
  /**
   * Number of models returned in this response (after pagination/filtering).
   */
  returned_count?: number;
  /**
   * Starting index for pagination (0 if not paginated).
   */
  offset?: number;
  limit?: number | null;
  /**
   * List of audit information for each model.
   */
  models: Array<ModelAuditInfo>;
  /**
   * Aggregate summary statistics.
   */
  summary: CategoryAuditSummary;
}
export namespace CategoryAuditResponse {}
