/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParameterBucketStats } from './parameterBucketStats';
import { DownloadStats } from './downloadStats';
import { BaselineStats } from './baselineStats';
import { MODEL_REFERENCE_CATEGORY } from './mODELREFERENCECATEGORY';
import { TagStats } from './tagStats';

/**
 * Comprehensive statistics for a model reference category.  Contains aggregate metrics, distributions, and metadata about all models in a category.
 */
export interface CategoryStatistics {
  /**
   * The category these statistics describe.
   */
  category: MODEL_REFERENCE_CATEGORY;
  /**
   * Total number of models in the category (before pagination).
   */
  total_models: number;
  /**
   * Number of models returned in this response (after pagination).
   */
  returned_models?: number;
  /**
   * Starting index for pagination (0 if not paginated).
   */
  offset?: number;
  limit?: number | null;
  /**
   * Number of NSFW models (if applicable to category).
   */
  nsfw_count?: number;
  /**
   * Distribution of models across different baselines.
   */
  baseline_distribution?: { [key: string]: BaselineStats };
  download_stats?: DownloadStats | null;
  /**
   * Top tags by frequency (for categories with tags).
   */
  top_tags?: Array<TagStats>;
  /**
   * Top styles by frequency (for categories with styles).
   */
  top_styles?: Array<TagStats>;
  /**
   * Distribution of text models by parameter count buckets (text generation only).
   */
  parameter_buckets?: Array<ParameterBucketStats>;
  /**
   * Number of models without parameter count information (text generation only).
   */
  models_without_param_info?: number;
  /**
   * Number of models with trigger words (image generation only).
   */
  models_with_trigger_words?: number;
  /**
   * Number of inpainting models (image generation only).
   */
  models_with_inpainting?: number;
  /**
   * Number of models with special requirements (image generation only).
   */
  models_with_requirements?: number;
  /**
   * Number of models with showcase links.
   */
  models_with_showcases?: number;
  /**
   * Unix timestamp when these statistics were computed.
   */
  computed_at: number;
}
export namespace CategoryStatistics {}
