/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Summary statistics for a category audit.  Aggregates audit information across all models in a category.
 */
export interface CategoryAuditSummary {
  /**
   * Total number of models in the category.
   */
  total_models: number;
  /**
   * Number of models with at least one deletion risk flag.
   */
  models_at_risk: number;
  /**
   * Number of models in critical state (zero month usage AND no workers).
   */
  models_critical: number;
  /**
   * Number of models with warning-level issues (host/download problems).
   */
  models_with_warnings: number;
  /**
   * Number of models with zero usage in the past day.
   */
  models_with_zero_day_usage?: number;
  /**
   * Number of models with zero usage in the past month.
   */
  models_with_zero_month_usage?: number;
  /**
   * Number of models with zero usage all-time.
   */
  models_with_zero_total_usage?: number;
  /**
   * Number of models with no active workers.
   */
  models_with_no_active_workers?: number;
  /**
   * Number of models without download URLs.
   */
  models_with_no_downloads?: number;
  /**
   * Number of models on non-preferred hosts.
   */
  models_with_non_preferred_hosts?: number;
  /**
   * Number of models with downloads across multiple hosts.
   */
  models_with_multiple_hosts?: number;
  /**
   * Number of models with very low usage (< 0.1% of category).
   */
  models_with_low_usage?: number;
  /**
   * Average risk score across all models.
   */
  average_risk_score: number;
  /**
   * Total monthly usage for the entire category.
   */
  category_total_month_usage?: number;
}
