/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelClassification } from './modelClassification';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';
import { FineTuneSeriesInfo } from './fineTuneSeriesInfo';

/**
 * A Codeformer model entry in the model reference.
 */
export interface CodeformerModelRecord {
  record_type?: string;
  name: string;
  description?: string | null;
  version?: string | null;
  finetune_series?: FineTuneSeriesInfo | null;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification?: ModelClassification;
}
