/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response from the name composition endpoint.
 */
export interface ComposeNameResponse {
  composed_name: string;
  already_exists: boolean;
  suggested_group: string;
}
