/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request body for composing a model name from parts.
 */
export interface ComposeNameRequest {
  author?: string | null;
  base_name: string;
  size: string;
  variant?: string | null;
  version?: string | null;
  quant?: string | null;
  separator?: string | null;
  part_order?: Array<string> | null;
}
