/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelClassification } from './modelClassification';
import { Style } from './style';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';

/**
 * A ControlNet model entry in the model reference.
 */
export interface ControlNetModelRecordInput {
  name: string;
  description?: string | null;
  version?: string | null;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification?: ModelClassification;
  style: Style;
}
