/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Flags indicating potential reasons for model deletion.  Each flag represents a specific issue that might warrant model removal. Aligned with frontend expectations for consistent presentation.
 */
export interface DeletionRiskFlags {
  /**
   * Model has no usage in the past day.
   */
  zero_usage_day?: boolean;
  /**
   * Model has no usage in the past month.
   */
  zero_usage_month?: boolean;
  /**
   * Model has no usage in total (all time).
   */
  zero_usage_total?: boolean;
  /**
   * Model has zero active workers (from Horde API data).
   */
  no_active_workers?: boolean;
  /**
   * Model downloads are distributed across multiple file hosts.
   */
  has_multiple_hosts?: boolean;
  /**
   * Model is hosted on non-preferred file hosts (non-HuggingFace).
   */
  has_non_preferred_host?: boolean;
  /**
   * Model has download URLs with unknown or unparseable hosts.
   */
  has_unknown_host?: boolean;
  /**
   * Model has no download URLs, empty download list, or invalid URLs.
   */
  no_download_urls?: boolean;
  /**
   * Model lacks a description field.
   */
  missing_description?: boolean;
  /**
   * Model lacks baseline information (for applicable categories).
   */
  missing_baseline?: boolean;
  /**
   * Model has very low usage (threshold defined by LOW_USAGE_THRESHOLD constant).
   */
  low_usage?: boolean;
}
