/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response containing sorted unique baseline values for text models.
 */
export interface DistinctBaselinesResponse {
  baselines: Array<string>;
}
