/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A record of a file to download for a model. Typically a ckpt file.
 */
export interface DownloadRecord {
  file_name: string;
  file_url: string;
  sha256sum?: string;
  file_purpose?: string | null;
  known_slow_download?: boolean | null;
}
