/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FieldChangeType } from './fieldChangeType';

/**
 * Field-level difference between before and after states.
 */
export interface FieldDiff {
  field_path: string;
  old_value?: null;
  new_value?: null;
  change_type: FieldChangeType;
}
export namespace FieldDiff {}
