/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelClassification } from './modelClassification';
import { ModelLicensing } from './modelLicensing';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';
import { FineTuneSeriesInfo } from './fineTuneSeriesInfo';

/**
 * A generic model reference record.
 */
export interface GenericModelRecord {
  record_type: string;
  name: string;
  description?: string | null;
  version?: string | null;
  finetune_series?: FineTuneSeriesInfo | null;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification: ModelClassification;
  size_on_disk_bytes?: number | null;
  licensing?: ModelLicensing | null;
}
