/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DownloadRecord } from './downloadRecord';

/**
 * Configuration for a generic model record.
 */
export interface GenericModelRecordConfig {
  download?: Array<DownloadRecord>;
}
