/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextModelGroupNameSchema } from './textModelGroupNameSchema';

/**
 * Response for a group\'s naming schema.
 */
export interface GroupNameSchemaResponse {
  group_name: string;
  name_schema: TextModelGroupNameSchema;
  is_custom: boolean;
}
