/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A single group alias entry.
 */
export interface GroupAliasResponse {
  canonical: string;
  aliases: Array<string>;
}
