/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParsedNameInfo } from './parsedNameInfo';

/**
 * A single member of a text model group with parsed name info.
 */
export interface GroupMemberInfo {
  name: string;
  parsed: ParsedNameInfo;
  parameters?: number | null;
  baseline?: string | null;
  nsfw?: boolean | null;
  description?: string | null;
  url?: string | null;
  style?: string | null;
  tags?: Array<string> | null;
  display_name?: string | null;
  instruct_format?: string | null;
  is_backend_duplicate?: boolean;
  backend_prefix?: string | null;
}
