/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextGuidanceChangeSet } from './textGuidanceChangeSet';

/**
 * Reviewable proposal synthesized from legacy instruct-format labels.
 */
export interface GuidanceMigrationPreview {
  change_set: TextGuidanceChangeSet | null;
  source_model_count: number;
  format_count: number;
}
