/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextGuidanceAssignment } from './textGuidanceAssignment';

/**
 * One explicit assignment replacement/removal with a reviewed prior value.
 */
export interface GuidanceAssignmentChange {
  model_name: string;
  assignment?: TextGuidanceAssignment | null;
  expected_before?: TextGuidanceAssignment | null;
}
