/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AIHordeStatus } from './aIHordeStatus';

/**
 * Enhanced heartbeat response with external service status.
 */
export interface HeartbeatResponse {
  status: string;
  ai_horde: AIHordeStatus;
}
