/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response for /{category}/last_updated endpoint.
 */
export interface HordeModelReferenceServiceV1RoutersMetadataCategoryLastUpdatedResponse {
  category: string;
  last_updated: number | null;
}
