/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextContextWindow } from './textContextWindow';
import { SupportClaim } from './supportClaim';
import { ImageGenerationModelRecordRequirementsValue } from './imageGenerationModelRecordRequirementsValue';
import { ModelLicensing } from './modelLicensing';

/**
 * Text generation legacy record with category-specific validation.
 */
export interface LegacyTextGenerationRecordOutput {
  name: string;
  type?: string | null;
  description?: string | null;
  version?: string | null;
  style?: string | null;
  nsfw?: boolean | null;
  download_all?: boolean | null;
  config?: object;
  available?: boolean | null;
  features_not_supported?: Array<string> | null;
  licensing?: ModelLicensing | null;
  model_name?: string | null;
  baseline?: string | null;
  parameters?: number | null;
  display_name?: string | null;
  url?: string | null;
  tags?: Array<string> | null;
  instruct_format?: string | null;
  settings?: { [key: string]: ImageGenerationModelRecordRequirementsValue } | null;
  context_window?: TextContextWindow | null;
  interaction_modes?: { [key: string]: SupportClaim } | null;
  capabilities?: { [key: string]: SupportClaim } | null;
}
