/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelLicensing } from './modelLicensing';

/**
 * CLIP legacy record with category-specific normalization.
 */
export interface LegacyClipRecordOutput {
  name: string;
  type?: LegacyClipRecordOutput.TypeEnum;
  description?: string | null;
  version?: string | null;
  style?: string | null;
  nsfw?: boolean | null;
  download_all?: boolean | null;
  config?: object;
  available?: boolean | null;
  features_not_supported?: Array<string> | null;
  licensing?: ModelLicensing | null;
  pretrained_name?: string | null;
}
export namespace LegacyClipRecordOutput {
  export const TypeEnum = {
    Clip: 'clip',
    Coca: 'coca',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
