/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegacyConfig } from './legacyConfig';

/**
 * Miscellaneous legacy record with category-specific normalization.
 */
export interface LegacyMiscellaneousRecordInput {
  [key: string]: any | any;

  name: string;
  type: LegacyMiscellaneousRecordInput.TypeEnum;
  description?: string | null;
  version?: string | null;
  style?: string | null;
  nsfw?: boolean | null;
  download_all?: boolean | null;
  config?: LegacyConfig;
  available?: boolean | null;
  features_not_supported?: Array<string> | null;
}
export namespace LegacyMiscellaneousRecordInput {
  export const TypeEnum = {
    LayerDiffuse: 'layer_diffuse',
  } as const;
  export type TypeEnum = (typeof TypeEnum)[keyof typeof TypeEnum];
}
