/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A single legacy config download entry.
 */
export interface LegacyConfigDownload {
  [key: string]: any | any;

  file_name?: string | null;
  file_path?: string | null;
  file_url?: string | null;
}
