/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A single legacy config file entry.
 */
export interface LegacyConfigFile {
  [key: string]: any | any;

  path: string;
  md5sum?: string | null;
  sha256sum?: string | null;
  file_type?: string | null;
}
