/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicensedAssetView } from './licensedAssetView';
import { LicensingDatasetMetadata } from './licensingDatasetMetadata';

/**
 * Represents a paginated collection of unified licensed assets.
 */
export interface LicensedAssetPage {
  items: Array<LicensedAssetView>;
  total: number;
  offset: number;
  limit: number;
  metadata: LicensingDatasetMetadata;
}
