/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseDefinition } from './licenseDefinition';
import { LicensingDatasetMetadata } from './licensingDatasetMetadata';

/**
 * Represents a paginated collection of normalized license definitions.
 */
export interface LicenseDefinitionPage {
  items: Array<LicenseDefinition>;
  total: number;
  offset: number;
  limit: number;
  metadata: LicensingDatasetMetadata;
}
