/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Represents one source supporting a scope-specific licensing conclusion.
 */
export interface LicenseEvidence {
  source: string;
  description?: string | null;
  checked_at?: string | null;
}
