/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseObligation } from './licenseObligation';
import { LicenseEvidence } from './licenseEvidence';
import { PermissionStatus } from './permissionStatus';

/**
 * Represents a reviewed license conclusion for one declared scope.
 */
export interface LicenseAssignment {
  license_expression: string;
  license_ids?: Array<string>;
  commercial_use: PermissionStatus;
  redistribution: PermissionStatus;
  obligations?: Array<LicenseObligation>;
  attribution?: string | null;
  evidence?: Array<LicenseEvidence>;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  notes?: string | null;
}
export namespace LicenseAssignment {}
