/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enum of all the model styles.
 */
export const MODEL_STYLE = {
  Generalist: 'generalist',
  Anime: 'anime',
  Furry: 'furry',
  Artistic: 'artistic',
  Other: 'other',
  Realistic: 'realistic',
} as const;
export type MODEL_STYLE = (typeof MODEL_STYLE)[keyof typeof MODEL_STYLE];
