/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseAssignment } from './licenseAssignment';
import { LicenseObligation } from './licenseObligation';
import { LicenseEvidence } from './licenseEvidence';
import { PermissionStatus } from './permissionStatus';

/**
 * Represents a model-level conclusion with optional per-download-file overrides.
 */
export interface ModelLicensing {
  license_expression: string;
  license_ids?: Array<string>;
  commercial_use: PermissionStatus;
  redistribution: PermissionStatus;
  obligations?: Array<LicenseObligation>;
  attribution?: string | null;
  evidence?: Array<LicenseEvidence>;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  notes?: string | null;
  files?: { [key: string]: LicenseAssignment };
}
export namespace ModelLicensing {}
