/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The categories of model reference entries.
 */
export const MODELREFERENCECATEGORY = {
  Blip: 'blip',
  Clip: 'clip',
  Codeformer: 'codeformer',
  Controlnet: 'controlnet',
  Esrgan: 'esrgan',
  Gfpgan: 'gfpgan',
  SafetyChecker: 'safety_checker',
  ImageGeneration: 'image_generation',
  TextGeneration: 'text_generation',
  VideoGeneration: 'video_generation',
  AudioGeneration: 'audio_generation',
  Miscellaneous: 'miscellaneous',
} as const;
export type MODELREFERENCECATEGORY =
  (typeof MODELREFERENCECATEGORY)[keyof typeof MODELREFERENCECATEGORY];
