/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Purpose } from './purpose';
import { Domain } from './domain';

/**
 * Contains specific information about how to categorize a model.  This includes the model\'s `MODEL_DOMAIN` and `MODEL_PURPOSE`.
 */
export interface ModelClassification {
  domain: Domain;
  purpose: Purpose;
}
