/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The domain of a model, i.e., what it pertains to (image, text, video, etc.).
 */
export const MODEL_DOMAIN = {
  Image: 'image',
  Text: 'text',
  Video: 'video',
  Audio: 'audio',
  Rendered3d: 'rendered_3d',
} as const;
export type MODEL_DOMAIN = (typeof MODEL_DOMAIN)[keyof typeof MODEL_DOMAIN];
