/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Set or clear a name schema exception on a model.
 */
export interface NameExceptionRequest {
  reason: string | null;
}
