/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGenerationModelRecordInputRequirementsValue } from './imageGenerationModelRecordInputRequirementsValue';
import { ModelClassification } from './modelClassification';
import { ImageGenerationModelRecordInput } from './imageGenerationModelRecordInput';
import { CONTROLNET_STYLE } from './cONTROLNETSTYLE';
import { GenericModelRecordInput } from './genericModelRecordInput';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';
import { TextGenerationModelRecordInput } from './textGenerationModelRecordInput';
import { MODEL_REFERENCE_CATEGORY } from './mODELREFERENCECATEGORY';
import { ControlNetModelRecordInput } from './controlNetModelRecordInput';

/**
 * A model record conforming to one of the category-specific schemas
 */
export interface NewModelRecord {
  record_type: MODEL_REFERENCE_CATEGORY;
  name: string;
  description?: string;
  version?: string;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification: ModelClassification;
  inpainting?: boolean;
  baseline: string;
  optimization?: string;
  tags?: Array<string>;
  showcases?: Array<string>;
  min_bridge_version?: number;
  trigger?: Array<string>;
  homepage?: string;
  nsfw: boolean;
  style?: string;
  requirements?: { [key: string]: ImageGenerationModelRecordInputRequirementsValue };
  size_on_disk_bytes?: number;
  parameters: number;
  display_name?: string;
  url?: string;
  settings?: { [key: string]: ImageGenerationModelRecordInputRequirementsValue };
  controlnet_style: CONTROLNET_STYLE;
}
export namespace NewModelRecord {}
