/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtraPartInfo } from './extraPartInfo';

/**
 * Structured result of parsing a text model name.
 */
export interface ParsedNameResponse {
  original_name: string;
  base_name: string;
  size?: string | null;
  variant?: string | null;
  quant?: string | null;
  version?: string | null;
  suggested_group: string;
  extras?: Array<ExtraPartInfo>;
}
