/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Kinds of resources carried by the shared review queue.
 */
export const PendingResourceKind = {
  ModelReference: 'model_reference',
  TextGuidance: 'text_guidance',
} as const;
export type PendingResourceKind = (typeof PendingResourceKind)[keyof typeof PendingResourceKind];
