/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingChangeStatus } from './pendingChangeStatus';
import { AuditOperation } from './auditOperation';
import { MODEL_REFERENCE_CATEGORY } from './mODELREFERENCECATEGORY';

/**
 * Single pending change tracked by the queue.
 */
export interface PendingChangeRecord {
  change_id: number;
  category: MODEL_REFERENCE_CATEGORY;
  model_name: string;
  operation: AuditOperation;
  payload?: { [key: string]: any } | null;
  requested_by: string;
  requested_username: string;
  requested_at?: number;
  status?: PendingChangeStatus;
  notes?: string | null;
  batch_id?: number | null;
  batch_title?: string | null;
  approved_by?: string | null;
  approved_username?: string | null;
  approved_at?: number | null;
  rejected_by?: string | null;
  rejected_username?: string | null;
  rejected_at?: number | null;
  reject_reason?: string | null;
  applied_at?: number | null;
  applied_by?: string | null;
  applied_username?: string | null;
  applied_job_id?: string | null;
  updated_at?: number;
  request_metadata?: { [key: string]: any } | null;
}
export namespace PendingChangeRecord {}
