/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request payload used to approve/reject queued changes.
 */
export interface PendingBatchRequest {
  batch_title: string;
  approved_ids?: Array<number> | null;
  rejected_ids?: Array<number> | null;
  reject_reason?: string | null;
}
