/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CanonicalFormat } from './canonicalFormat';
import { PendingQueueAuditChange } from './pendingQueueAuditChange';

/**
 * Snapshot of currently pending (unapproved) changes.
 */
export interface PendingQueueAuditCurrentResponse {
  domain: CanonicalFormat;
  pending_changes: Array<PendingQueueAuditChange>;
  total_pending: number;
  generated_at: number;
}
export namespace PendingQueueAuditCurrentResponse {}
