/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingChangeStatus } from './pendingChangeStatus';
import { PendingQueueAuditEvent } from './pendingQueueAuditEvent';
import { AuditOperation } from './auditOperation';
import { MODEL_REFERENCE_CATEGORY } from './mODELREFERENCECATEGORY';

/**
 * Lifecycle view of a pending change reconstructed from audit events.
 */
export interface PendingQueueAuditChange {
  change_id: number;
  status: PendingChangeStatus;
  operation?: AuditOperation | null;
  category?: MODEL_REFERENCE_CATEGORY | null;
  model_name?: string | null;
  requested_by?: string | null;
  requested_at?: number | null;
  approved_by?: string | null;
  approved_at?: number | null;
  rejected_by?: string | null;
  rejected_at?: number | null;
  reject_reason?: string | null;
  applied_by?: string | null;
  applied_at?: number | null;
  applied_job_id?: string | null;
  batch_id?: number | null;
  batch_title?: string | null;
  events?: Array<PendingQueueAuditEvent>;
}
export namespace PendingQueueAuditChange {}
