/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Lifecycle states for queued changes.
 */
export const PendingChangeStatus = {
  Pending: 'pending',
  Approved: 'approved',
  Applied: 'applied',
  Rejected: 'rejected',
} as const;
export type PendingChangeStatus = (typeof PendingChangeStatus)[keyof typeof PendingChangeStatus];
