/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PromptMessage } from './promptMessage';

/**
 * Portable input messages and their expected serialized prompt.
 */
export interface PromptExample {
  title: string;
  description?: string | null;
  messages: Array<PromptMessage>;
  rendered_prompt?: string | null;
}
