/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PendingChangeStatus } from './pendingChangeStatus';
import { MODEL_REFERENCE_CATEGORY } from './mODELREFERENCECATEGORY';

/**
 * Request payload to purge pending changes matching a filter.
 */
export interface PurgePendingChangesRequest {
  statuses?: Array<PendingChangeStatus> | null;
  categories?: Array<MODEL_REFERENCE_CATEGORY> | null;
  model_name?: string | null;
  requested_by?: Array<string> | null;
  purge_all?: boolean;
  dry_run?: boolean;
}
