/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Indicates if copies of the model reference are canonical or replicated.
 */
export const ReplicateMode = {
  Primary: 'PRIMARY',
  Replica: 'REPLICA',
} as const;
export type ReplicateMode = (typeof ReplicateMode)[keyof typeof ReplicateMode];
