/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextPromptContract } from './textPromptContract';
import { TextGuidanceSummary } from './textGuidanceSummary';
import { TextGuidanceCatalogMetadata } from './textGuidanceCatalogMetadata';
import { TextUsageRecipe } from './textUsageRecipe';

/**
 * Fully resolved guidance for one exact text model.
 */
export interface ResolvedTextGuidance {
  model_name: string;
  summary: TextGuidanceSummary;
  primary_profile?: TextPromptContract | null;
  supplemental_profiles?: Array<TextUsageRecipe>;
  legacy_instruct_format?: string | null;
  catalog_metadata: TextGuidanceCatalogMetadata;
}
