/**
 * FastAPI
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * Post-processed by generate-api-client.js to produce a proper union type.
 */
import { ImageGenerationModelRecordOutput } from './imageGenerationModelRecordOutput';
import { TextGenerationModelRecordOutput } from './textGenerationModelRecordOutput';
import { ControlNetModelRecordOutput } from './controlNetModelRecordOutput';
import { GenericModelRecordOutput } from './genericModelRecordOutput';

export type ResponseReadV2ReferenceValue =
  | ImageGenerationModelRecordOutput
  | TextGenerationModelRecordOutput
  | ControlNetModelRecordOutput
  | GenericModelRecordOutput;
