/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GenericModelRecordOutput } from './genericModelRecordOutput';
import { ImageGenerationModelRecordInputRequirementsValue } from './imageGenerationModelRecordInputRequirementsValue';
import { ModelClassification } from './modelClassification';
import { Style } from './style';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';
import { ControlNetModelRecordOutput } from './controlNetModelRecordOutput';
import { ImageGenerationModelRecordOutput } from './imageGenerationModelRecordOutput';
import { TextGenerationModelRecordOutput } from './textGenerationModelRecordOutput';

/**
 * A model record conforming to one of the category-specific schemas
 */
export interface ResponseCreateModelModelReferencesV2ModelCategoryNameAddPost {
  name: string;
  description?: string;
  version?: string;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification: ModelClassification;
  inpainting?: boolean;
  baseline: string;
  optimization?: string;
  tags?: Array<string>;
  showcases?: Array<string>;
  min_bridge_version?: number;
  trigger?: Array<string>;
  homepage?: string;
  nsfw: boolean;
  style: Style;
  requirements?: { [key: string]: ImageGenerationModelRecordInputRequirementsValue };
  size_on_disk_bytes?: number;
  parameters: number;
  display_name?: string;
  url?: string;
  settings?: { [key: string]: ImageGenerationModelRecordInputRequirementsValue };
}
