/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuidanceSource } from './guidanceSource';
import { SupportStatus } from './supportStatus';

/**
 * Reviewed durable support conclusion with optional evidence.
 */
export interface SupportClaim {
  status: SupportStatus;
  sources?: Array<GuidanceSource>;
  qualification?: string | null;
}
export namespace SupportClaim {}
