/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Statistics about model tags or styles.
 */
export interface TagStats {
  /**
   * The tag or style name.
   */
  tag: string;
  /**
   * Number of models with this tag/style.
   */
  count: number;
  /**
   * Percentage of total models with this tag/style.
   */
  percentage: number;
}
