/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Declared variable accepted by a raw prompting template.
 */
export interface TemplateVariable {
  name: string;
  description: string;
  required?: boolean;
}
