/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Durable ways in which a text model accepts prompts.
 */
export const TextInteractionMode = {
  Completion: 'completion',
  Instruction: 'instruction',
  Chat: 'chat',
} as const;
export type TextInteractionMode = (typeof TextInteractionMode)[keyof typeof TextInteractionMode];
