/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GuidanceSource } from './guidanceSource';
import { GuidanceRecordMetadata } from './guidanceRecordMetadata';
import { ParametersValue } from './parametersValue';
import { PromptExample } from './promptExample';
import { GuidanceAudienceContent } from './guidanceAudienceContent';
import { AIHordeRequestExample } from './aIHordeRequestExample';
import { TextCapability } from './textCapability';

/**
 * Reusable scenario guidance that supplements a prompt contract.
 */
export interface TextUsageRecipe {
  profile_id: string;
  kind?: TextUsageRecipe.KindEnum;
  display_name: string;
  aliases?: Array<string>;
  summary: string;
  user?: GuidanceAudienceContent;
  developer?: GuidanceAudienceContent;
  examples?: Array<PromptExample>;
  recommended_settings?: { [key: string]: ParametersValue };
  ai_horde_examples?: Array<AIHordeRequestExample>;
  sources?: Array<GuidanceSource>;
  deprecated?: boolean;
  metadata?: GuidanceRecordMetadata;
  capability?: TextCapability | null;
  scenario?: string | null;
}
export namespace TextUsageRecipe {
  export const KindEnum = {
    UsageRecipe: 'usage_recipe',
  } as const;
  export type KindEnum = (typeof KindEnum)[keyof typeof KindEnum];
}
