/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextGuidanceStatus } from './textGuidanceStatus';

/**
 * Compact guidance projection embedded in text-model reads.
 */
export interface TextGuidanceSummary {
  status: TextGuidanceStatus;
  primary_profile_id?: string | null;
  supplemental_profile_ids?: Array<string>;
}
export namespace TextGuidanceSummary {}
