/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelClassification } from './modelClassification';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';
import { FineTuneSeriesInfo } from './fineTuneSeriesInfo';

/**
 * A textual inversion (embedding) model entry in the model reference.  Like :class:`LoraModelRecord`, textual inversions are ``managed_elsewhere`` and are normally supplied by third-party providers.
 */
export interface TextualInversionModelRecord {
  record_type?: string;
  name: string;
  description?: string | null;
  version?: string | null;
  finetune_series?: FineTuneSeriesInfo | null;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification?: ModelClassification;
  baseline?: string | null;
  nsfw?: boolean;
  tags?: Array<string> | null;
  trigger?: Array<string> | null;
  homepage?: string | null;
  showcases?: Array<string> | null;
}
