/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Consumer-facing guidance availability state for an exact model.
 */
export const TextGuidanceStatus = {
  Published: 'published',
  LegacyLabel: 'legacy_label',
  Undocumented: 'undocumented',
} as const;
export type TextGuidanceStatus = (typeof TextGuidanceStatus)[keyof typeof TextGuidanceStatus];
