/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Machine-consumable text capabilities tracked by the reference.
 */
export const TextCapability = {
  ToolCalling: 'tool_calling',
  StructuredOutput: 'structured_output',
} as const;
export type TextCapability = (typeof TextCapability)[keyof typeof TextCapability];
