/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TextContextWindow } from './textContextWindow';
import { SupportClaim } from './supportClaim';
import { ImageGenerationModelRecordRequirementsValue } from './imageGenerationModelRecordRequirementsValue';
import { ModelClassification } from './modelClassification';
import { ModelLicensing } from './modelLicensing';
import { TextGuidanceSummary } from './textGuidanceSummary';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';
import { FineTuneSeriesInfo } from './fineTuneSeriesInfo';

/**
 * A text generation model entry in the model reference.
 */
export interface TextGenerationModelRecord {
  record_type?: string;
  name: string;
  description?: string | null;
  version?: string | null;
  finetune_series?: FineTuneSeriesInfo | null;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification?: ModelClassification;
  size_on_disk_bytes?: number | null;
  licensing?: ModelLicensing | null;
  baseline?: string | null;
  parameters: number;
  nsfw?: boolean;
  style?: string | null;
  display_name?: string | null;
  url?: string | null;
  tags?: Array<string> | null;
  instruct_format?: string | null;
  settings?: { [key: string]: ImageGenerationModelRecordRequirementsValue } | null;
  text_model_group?: string | null;
  name_schema_exception?: string | null;
  context_window?: TextContextWindow | null;
  interaction_modes?: { [key: string]: SupportClaim } | null;
  capabilities?: { [key: string]: SupportClaim } | null;
  guidance?: TextGuidanceSummary | null;
}
