/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ImageGenerationModelRecordInputRequirementsValue } from './imageGenerationModelRecordInputRequirementsValue';
import { ModelClassification } from './modelClassification';
import { GenericModelRecordConfig } from './genericModelRecordConfig';
import { GenericModelRecordMetadata } from './genericModelRecordMetadata';

/**
 * A text generation model entry in the model reference.
 */
export interface TextGenerationModelRecordInput {
  name: string;
  description?: string | null;
  version?: string | null;
  metadata?: GenericModelRecordMetadata;
  config?: GenericModelRecordConfig;
  model_classification?: ModelClassification;
  baseline?: string | null;
  parameters: number;
  nsfw?: boolean;
  style?: string | null;
  display_name?: string | null;
  url?: string | null;
  tags?: Array<string> | null;
  settings?: { [key: string]: ImageGenerationModelRecordInputRequirementsValue } | null;
}
