/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProfilesValue } from './profilesValue';
import { TextGuidanceCatalogMetadata } from './textGuidanceCatalogMetadata';
import { TextGuidanceAssignment } from './textGuidanceAssignment';

/**
 * Atomic machine-readable catalog of profiles and explicit assignments.
 */
export interface TextGuidanceCatalog {
  metadata?: TextGuidanceCatalogMetadata;
  profiles?: { [key: string]: ProfilesValue };
  assignments?: { [key: string]: TextGuidanceAssignment };
}
