/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Usage trend metrics comparing different time periods.  Ratios help identify model momentum and activity patterns.
 */
export interface UsageTrend {
  day_to_month_ratio?: number | null;
  month_to_total_ratio?: number | null;
}
