/**
 * Horde Model Reference API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Response model for the user roles endpoint.
 */
export interface UserRolesResponse {
  user_id: string;
  username: string;
  roles: Array<string>;
  is_approver: boolean;
  is_requestor: boolean;
  is_license_editor: boolean;
}
